title_left: Think
title_right: space
description: Minimalist Jekyll theme for technical writing blog.
keywords: 'Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace'
url: ''
baseurl: ''
cover: ''
google_analytics: UA-XXXXX-XX
twitter_username: ''
comments_enabled: false
disqus_shortname: ''
postshare_enabled: false
permalink: '/:year/:title/'
markdown: kramdown
highlighter: rouge
source: ./
destination: ./_site
sass:
  sass_dir: assets/scss
  style: compressed
author:
  name: John Doe
plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
exclude:
  - gulp
  - node_modules
  - bower
  - bower_components
  - config.rb
  - src
  - Gemfile
  - Gemfile.lock
  - .rvmrc
  - .rbenv-version
  - package.json
  - gulpfile.js
  - README.md
  - Rakefile
  - changelog.md
  - script
  - vendor
  - thinkspace.gemspec
